name: CICD

on:
  workflow_dispatch:
    inputs:
      member:
        description: 'Member'
        required: true
      youlog:
        description: 'Youlog'
        required: true
      version:
        description: 'Version'
        required: true
      repo:
        description: 'Repo'
        required: true
      tag:
        description: 'Tag'
        required: true
      sub_dir:
        description: 'Sub Dir'
        required: true

jobs:
  build:

    runs-on: ubuntu-latest

    # permissions:
    #   contents: write

    # strategy:
    #   matrix:
    #     node-version: [20.x]

    steps:
    - name: Checkout
      uses: actions/checkout@v4


    - name: dist
      run: |
        echo "${{ secrets.SSH_KEY_DEPLOY_ED25519 }}" > id_rsa_daobox && chmod 600 id_rsa_daobox
        export QINIU_ACCESS_KEY=${{ secrets.QINIU_ACCESS_KEY }}
        export QINIU_SECRET_KEY=${{ secrets.QINIU_SECRET_KEY }}

        # 构建
        make all-in-one MEMBER=${{ inputs.member }} YOULOG=${{ inputs.youlog }} VERSION=${{ inputs.version }} REPO=${{ inputs.repo }} TAG=${{ inputs.tag }} SUB_DIR=${{ inputs.sub_dir }}

        # 配置 ssh 密钥
        mkdir -p ~/.ssh
        chmod 700 ~/.ssh
        touch ~/.ssh/known_hosts
        chmod 600 ~/.ssh/known_hosts
        echo "${{ secrets.Y5_EVERKM_COM_HOST_KEY }}" >> ~/.ssh/known_hosts

        # 部署
        echo "deploying to y5.everkm.com"
        ssh -i id_rsa_daobox -p 11022 root@y5.everkm.com "mkdir -p /data/www/youlog-www/${{ inputs.member }}/${{ inputs.youlog }}"
        scp -i id_rsa_daobox -P 11022 tmp/${{ inputs.youlog }}@${{ inputs.version }}.zip root@y5.everkm.com:/data/www/youlog-www/${{ inputs.member }}/${{ inputs.youlog }}/

